{
 "title": "IOT CORE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/status\")"
    }
   ]
  },
  {
   "title": "Mean Roll",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/rotationX\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Pitch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/rotationY\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Yaw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/rotationZ\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Acceleration X",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/accelerationX\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Acceleration Y",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/accelerationY\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Acceleration Z",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/accelerationZ\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/temperature\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Imbalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/imbalance_est_kf\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Current (R)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/current_R\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Current (S)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/current_S\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Mean Current (T)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/current_T\")\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "Horímetro",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/horimetro\")"
    }
   ]
  },
  {
   "title": "Velocidade Angular Triaxial",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/rotationX\" or r._measurement == \"esp32/rotationY\" or r._measurement == \"esp32/rotationZ\")"
    }
   ]
  },
  {
   "title": "Desbalanceamento de Fase (Real / Estimado)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/imbalance\" or r._measurement == \"esp32/imbalance_est_kf\")"
    }
   ]
  },
  {
   "title": "Measured Current Value",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/current_R\" or r._measurement == \"esp32/current_S\" or r._measurement == \"esp32/current_T\")"
    }
   ]
  },
  {
   "title": "Linha do Tempo de Operação",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/status\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/watt_R\" or r._measurement == \"esp32/watt_S\" or r._measurement == \"esp32/watt_T\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/accelerationX\" or r._measurement == \"esp32/accelerationY\" or r._measurement == \"esp32/accelerationZ\")"
    }
   ]
  },
  {
   "title": "Status do Ativo",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/status\")"
    }
   ]
  },
  {
   "title": "Aceleração Triaxial",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/accelerationX\" or r._measurement == \"esp32/accelerationY\" or r._measurement == \"esp32/accelerationZ\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/rotationX\" or r._measurement == \"esp32/rotationY\" or r._measurement == \"esp32/rotationZ\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/imbalance\" or r._measurement == \"esp32/imbalance_est_kf\" or r._measurement == \"esp32/temperature\")"
    }
   ]
  },
  {
   "title": "Potência Aparente Trifásica",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/watt_R\" or r._measurement == \"esp32/watt_S\" or r._measurement == \"esp32/watt_T\")"
    }
   ]
  },
  { "title": "ALARMES", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 } },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/temperature\")"
    }
   ]
  },
  {
   "title": "Imbalance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -30m)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/imbalance_est_kf\")"
    }
   ]
  },
  {
   "title": "Corrente Trifásica",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"IOT\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"esp32/current_R\" or r._measurement == \"esp32/current_S\" or r._measurement == \"esp32/current_T\")"
    }
   ]
  }
 ]
}